services:
  web-app:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: "postgres:14.4"
    restart: always
    ports:
      - 5432:5432
    volumes:
      - data:/db/data
    environment:
      POSTGRES_DB: project
      POSTGRES_PASSWORD: root
volumes:
  data: